package science.aist.neo4j.it.namespace;

import science.aist.neo4j.namespace.annotations.ExtensionField;
import org.neo4j.ogm.annotation.NodeEntity;

import java.util.List;

/**
 * @author Oliver Krauss
 * @since 1.0
 */
@NodeEntity
public class NodeWithExtensions {

    /**
     * Id generated by database
     */
    private Long id;

    /**
     * Field that exists in the root class
     */
    private String fieldInClass;

    /**
     * Field that exists in the root class
     */
    @ExtensionField(name = "random_extension_field")
    private String extendingField;

    /**
     * Field that exists in the root class
     */
    @ExtensionField(name = "random_extension_collection")
    private List<String> extendingCollectionField;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFieldInClass() {
        return fieldInClass;
    }

    public void setFieldInClass(String fieldInClass) {
        this.fieldInClass = fieldInClass;
    }

    public String getExtendingField() {
        return extendingField;
    }

    public void setExtendingField(String extendingField) {
        this.extendingField = extendingField;
    }

    public List<String> getExtendingCollectionField() {
        return extendingCollectionField;
    }

    public void setExtendingCollectionField(List<String> extendingCollectionField) {
        this.extendingCollectionField = extendingCollectionField;
    }
}
