package science.aist.neo4j.it.nodes;

import org.neo4j.ogm.annotation.Relationship;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Andreas Pointner
 * @since 1.0
 */
public class TestNode {

    /**
     * Id generated by database
     */
    private Long id;

    /**
     * Problem statement the algorithm was supposed to solve
     */
    @Relationship(type = "FIELDS", direction = Relationship.OUTGOING)
    FieldRelationship testing;

    @Relationship(type = "MULTIS")
    List<MultiFieldRelationship> multiTesting = new ArrayList<>();

    public TestNode() {
    }

    public TestNode(FieldRelationship testing) {
        this.testing = testing;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public FieldRelationship getTesting() {
        return testing;
    }

    public void setTesting(FieldRelationship testing) {
        this.testing = testing;
    }

    public List<MultiFieldRelationship> getMultiTesting() {
        return multiTesting;
    }

    public void setMultiTesting(List<MultiFieldRelationship> multiTesting) {
        this.multiTesting = multiTesting;
    }
}
